debug: false

spring.jpa.show-sql: true
spring.jpa.generate-ddl: false
spring.rabbitmq.host: localhost
spring.rabbitmq.port: 5672
spring.rabbitmq.username: guest
spring.rabbitmq.password: guest

com.sap.icd.odatav2.spring:
   servicePath: holidayapp
   persistenceUnit: holiday-app
   language: en
   country: US
management:
  context-path: /admin
  security:
    enabled: false
---
spring:
    h2:
      console:
        enabled: true
        path: /console
    profiles: default
    datasource:
      username: sa
      password:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:~/holidayappdb
      
server:
    port: 8083      